kind: pipeline
type: docker
name: imgbox-deploy

volumes:
  - name: node_modules
    host:
      path: /volumes/drone/volumes/blog/node_modules
  - name: deploy_path
    host: 
      path: /opt/1panel/apps/openresty/openresty/www/sites/imgbox.irchat.cn/index

steps:
  - name: deploy
    image: node:22
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: deploy_path
        path: /drone/src/build
    commands:
      - npm config set registry https://registry.npmmirror.com/
      - npm install -g pnpm
      - pnpm config set registry https://registry.npmmirror.com/
      - pnpm install
      - pnpm run build
