kind: pipeline
type: docker
name: imgbox-deploy

volumes:
  - name: node_modules
    host:
      path: /volumes/drone/volumes/blog/node_modules
  - name: deploy_path
    host: 
      path: /opt/1panel/apps/openresty/openresty/www/sites/imgbox.irchat.cn

steps:
  - name: deploy
    image: node:16.13.2
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: deploy_path
        path: /drone/src/dist
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build
